[package]
name = "hfile"
version = "0.1.0"
edition = "2021"

[dependencies]
clearscreen = "2.0.1"
colored = "2.1.0"
image = "0.24.9"
lazy_static = "1.4.0"
rand = "0.8.5"
syntect = "5.2.0"
terminal_size = "0.3.0"
